name: compass-docs-env
channels:
  - conda-forge
dependencies:
  - python[version='>=3.9']
  - numpy
  - lxml
  - gdal[version='>=3']
  - pandas
  - pyproj
  - pysolid
  - pytest
  - ruamel.yaml
  - scipy
  - yamale
  - h5py
  - shapely
  - requests
